# Generated by Django 6.0.7 on 2026-07-24 02:51

import apps.returns.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_number",
                    models.CharField(
                        default=apps.returns.models.generate_return_number,
                        editable=False,
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PRODUCT_RECEIVED", "Product Received"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=30,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged Product"),
                            ("WRONG_PRODUCT", "Wrong Product"),
                            ("DEFECTIVE", "Defective Product"),
                            ("NOT_AS_DESCRIBED", "Product Not as Described"),
                            ("SIZE_OR_FIT", "Size or Fit Issue"),
                            ("CHANGED_MIND", "Changed Mind"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("stock_restored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["return_number"], name="returns_ret_return__7635ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["customer", "status"], name="returns_ret_custome_76a571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["order", "status"], name="returns_ret_order_i_7316d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "created_at"], name="returns_ret_status_51132c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.UniqueConstraint(
                fields=("return_request", "order_item"),
                name="unique_order_item_per_return_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="return_item_quantity_greater_than_zero",
            ),
        ),
    ]
