# Generated by Django 6.0.7 on 2026-07-24 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0003_alter_address_options_and_more"),
        ("products", "0001_initial"),
        ("returns", "0001_initial"),
        ("variants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RESTOCK", "Restock"),
                            ("SALE", "Sale"),
                            ("ORDER_CANCELLED", "Order Cancelled"),
                            ("RETURN_RECEIVED", "Return Received"),
                            ("MANUAL_INCREASE", "Manual Increase"),
                            ("MANUAL_DECREASE", "Manual Decrease"),
                            ("CORRECTION", "Stock Correction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("previous_stock", models.PositiveIntegerField()),
                ("new_stock", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.order",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="returns.returnrequest",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="variants.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"],
                        name="inventory_s_product_5919a9_idx",
                    ),
                    models.Index(
                        fields=["variant", "created_at"],
                        name="inventory_s_variant_183f66_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "created_at"],
                        name="inventory_s_movemen_ed5291_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "created_at"],
                        name="inventory_s_perform_ebc570_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_change", 0), _negated=True),
                        name="stock_movement_quantity_not_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("product__isnull", False), ("variant__isnull", True)
                            ),
                            models.Q(
                                ("product__isnull", True), ("variant__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="stock_movement_has_one_target",
                    ),
                ],
            },
        ),
    ]
