# Generated by Django 6.0.7 on 2026-07-24 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSecurityProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_email", models.EmailField(blank=True, max_length=254)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_verification_email_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_password_reset_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["verified_email"], name="account_sec_verifie_410411_idx"
                    ),
                    models.Index(
                        fields=["email_verified_at"],
                        name="account_sec_email_v_e80383_idx",
                    ),
                ],
            },
        ),
    ]
