# Generated by Django 6.0.7 on 2026-07-24 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_security", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier_hash", models.CharField(db_index=True, max_length=64)),
                ("identifier_hint", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("successful", models.BooleanField(default=False)),
                (
                    "failure_reason",
                    models.CharField(
                        choices=[
                            ("INVALID_CREDENTIALS", "Invalid Credentials"),
                            ("IDENTIFIER_BLOCKED", "Identifier Temporarily Blocked"),
                            ("IP_BLOCKED", "IP Address Temporarily Blocked"),
                            ("INACTIVE_ACCOUNT", "Inactive Account"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=40,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identifier_hash", "successful", "created_at"],
                        name="account_sec_identif_4f21a3_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "successful", "created_at"],
                        name="account_sec_ip_addr_853fc2_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="account_sec_user_id_7d2b62_idx",
                    ),
                    models.Index(
                        fields=["failure_reason", "created_at"],
                        name="account_sec_failure_fbee19_idx",
                    ),
                ],
            },
        ),
    ]
