"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def config_list(name, default=""):
    return [
        item.strip()
        for item in config(name, default=default).split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config_list(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
)


# Application definition

INSTALLED_APPS = [
    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party applications
    "rest_framework",
    "corsheaders",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",

    # Local applications
    "apps.accounts.apps.AccountsConfig",
    "apps.products.apps.ProductsConfig",
    "apps.carts.apps.CartsConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.tickets.apps.TicketsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.reviews.apps.ReviewsConfig",
    "apps.returns.apps.ReturnsConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.wishlists.apps.WishlistsConfig",
    "apps.coupons.apps.CouponsConfig",
    "apps.shipments.apps.ShipmentsConfig",
    "apps.reports.apps.ReportsConfig",
    "apps.banners.apps.BannersConfig",
    "apps.recently_viewed.apps.RecentlyViewedConfig",
    "apps.variants.apps.VariantsConfig",
    "apps.inventory.apps.InventoryConfig",
    "apps.shipping_rates.apps.ShippingRatesConfig",
    "apps.store_settings.apps.StoreSettingsConfig",
    "apps.account_security.apps.AccountSecurityConfig",
    "apps.email_notifications.apps.EmailNotificationsConfig",
    "apps.audit_logs.apps.AuditLogsConfig",
    "apps.api_security.apps.ApiSecurityConfig",
    "apps.system_health.apps.SystemHealthConfig",
    
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "apps.audit_logs.business_middleware.BusinessAuditContextMiddleware",
    "apps.audit_logs.middleware.AuditLogMiddleware",
    "apps.store_settings.middleware.StoreMaintenanceMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = config("TIME_ZONE", default="Asia/Karachi")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        (
            "rest_framework_simplejwt.authentication."
            "JWTAuthentication"
        ),
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    "DEFAULT_FILTER_BACKENDS": [
        (
            "django_filters.rest_framework."
            "DjangoFilterBackend"
        ),
    ],

    "DEFAULT_SCHEMA_CLASS": (
        "drf_spectacular.openapi.AutoSchema"
    ),

    "EXCEPTION_HANDLER": (
        "apps.api_security.exception_handler."
        "custom_exception_handler"
    ),

    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        (
            "apps.api_security.throttles."
            "BurstRateThrottle"
        ),
        (
            "apps.api_security.throttles."
            "SustainedRateThrottle"
        ),
        "rest_framework.throttling.ScopedRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/minute",
        "burst": "120/minute",
        "sustained": "5000/day",

        "register": "5/hour",
        "secure_login": "10/minute",
        "token_refresh": "30/minute",

        "password_email": "5/hour",
        "password_reset": "10/hour",

        "verification_email": "5/hour",
        "verification_confirm": "10/hour",

        "checkout": "10/minute",
        "shipping_quote": "30/minute",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=10,
    ),

    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7,
    ),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,

    "UPDATE_LAST_LOGIN": False,

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),

    "AUTH_HEADER_NAME": (
        "HTTP_AUTHORIZATION"
    ),

    "USER_ID_FIELD": "id",

    "USER_ID_CLAIM": "user_id",

    "TOKEN_TYPE_CLAIM": "token_type",

    "JTI_CLAIM": "jti",
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOW_STOCK_THRESHOLD = 5
RETURN_WINDOW_DAYS = 7

# Email configuration for local development
EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
)

DEFAULT_FROM_EMAIL = "noreply@ecommerce.local"

FRONTEND_URL = config(
    "FRONTEND_URL",
    default="http://localhost:5173",
)

# One hour
PASSWORD_RESET_TIMEOUT = 60 * 60

# Twenty-four hours
EMAIL_VERIFICATION_TIMEOUT = 60 * 60 * 24

# Prevent repeated email requests
ACCOUNT_EMAIL_COOLDOWN_SECONDS = 60

# Login security settings
LOGIN_MAX_IDENTIFIER_ATTEMPTS = 5
LOGIN_MAX_IP_ATTEMPTS = 20
LOGIN_LOCKOUT_MINUTES = 15

CACHES = {
    "default": {
        "BACKEND": (
            "django.core.cache.backends.locmem.LocMemCache"
        ),
        "LOCATION": "ecommerce-api-throttle-cache",
    }
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Ecommerce Web API",

    "DESCRIPTION": (
        "REST API documentation for the Ecommerce Web "
        "platform, including authentication, catalog, "
        "cart, checkout, orders, payments, returns, "
        "inventory and administration."
    ),

    "VERSION": "1.0.0",

    "SERVE_INCLUDE_SCHEMA": False,

    "COMPONENT_SPLIT_REQUEST": True,

    "SORT_OPERATIONS": True,

    "ENABLE_DJANGO_DEPLOY_CHECK": True,

    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayRequestDuration": True,
        "displayOperationId": True,
        "filter": True,
        "tryItOutEnabled": True,
    },

    "REDOC_UI_SETTINGS": {
        "hideDownloadButton": False,
        "expandResponses": "200,201",
        "pathInMiddlePanel": True,
    },

    "CONTACT": {
        "name": "Ecommerce Web Support",
        "email": "support@example.com",
    },
}

ENABLE_API_DOCS = config(
    "ENABLE_API_DOCS",
    default=DEBUG,
    cast=bool,
)

CORS_ALLOWED_ORIGINS = config_list(
    "CORS_ALLOWED_ORIGINS",
    default=(
        f"{FRONTEND_URL},"
        "http://127.0.0.1:5173"
    ),
)

CSRF_TRUSTED_ORIGINS = config_list(
    "CSRF_TRUSTED_ORIGINS",
    default=(
        f"{FRONTEND_URL},"
        "http://127.0.0.1:5173"
    ),
)
