# Generated by Django 6.0.7 on 2026-07-24 04:08

import apps.banners.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.banners.models.banner_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.banners.models.validate_banner_image_size,
                        ],
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.banners.models.banner_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.banners.models.validate_banner_image_size,
                        ],
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("HERO", "Hero Banner"),
                            ("PROMOTIONAL", "Promotional Banner"),
                            ("CATEGORY", "Category Banner"),
                            ("SIDEBAR", "Sidebar Banner"),
                        ],
                        default="HERO",
                        max_length=20,
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=100)),
                ("button_url", models.CharField(blank=True, max_length=500)),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional hexadecimal background color.",
                        max_length=20,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional hexadecimal text color.",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_banners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["position", "is_active", "display_order"],
                        name="banners_ban_positio_015437_idx",
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"],
                        name="banners_ban_starts__05252f_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("display_order__gte", 0)),
                        name="banner_display_order_not_negative",
                    )
                ],
            },
        ),
    ]
