# Generated by Django 6.0.7 on 2026-07-24 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("orders", "0002_order_coupon_code_order_discount_amount"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_recipie_86ea8b_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ORDER_STATUS", "Order Status"),
                    ("PAYMENT_STATUS", "Payment Status"),
                    ("TICKET_REPLY", "Ticket Reply"),
                    ("TICKET_STATUS", "Ticket Status"),
                    ("TICKET_ASSIGNED", "Ticket Assigned"),
                    ("RETURN_STATUS", "Return Status"),
                    ("SHIPMENT_STATUS", "Shipment Status"),
                    ("SYSTEM", "System"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="tickets.ticket",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="notificatio_recipie_4e3567_idx"
            ),
        ),
    ]
