# Generated by Django 6.0.7 on 2026-07-24 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("EMAIL_VERIFICATION", "Email Verification"),
                            ("CHECKOUT", "Checkout"),
                            ("ORDER_CANCEL", "Order Cancellation"),
                            ("STATUS_CHANGE", "Status Change"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=1000)),
                ("route_name", models.CharField(blank=True, max_length=255)),
                ("status_code", models.PositiveIntegerField(default=200)),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs__user_id_d31e2a_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs__action_70fdcf_idx",
                    ),
                    models.Index(
                        fields=["success", "created_at"],
                        name="audit_logs__success_a86ddc_idx",
                    ),
                    models.Index(
                        fields=["status_code", "created_at"],
                        name="audit_logs__status__67ddc5_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="audit_logs__ip_addr_26abee_idx",
                    ),
                    models.Index(
                        fields=["method", "created_at"],
                        name="audit_logs__method_faf2dd_idx",
                    ),
                ],
            },
        ),
    ]
