# Generated by Django 6.0.7 on 2026-07-24 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PRODUCT_CREATED", "Product Created"),
                            ("PRODUCT_UPDATED", "Product Updated"),
                            ("PRODUCT_DELETED", "Product Deleted"),
                            ("COUPON_CREATED", "Coupon Created"),
                            ("COUPON_UPDATED", "Coupon Updated"),
                            ("COUPON_DELETED", "Coupon Deleted"),
                            ("STOCK_MOVEMENT", "Stock Movement"),
                            ("RETURN_CREATED", "Return Created"),
                            ("RETURN_STATUS_CHANGED", "Return Status Changed"),
                            ("PAYMENT_STATUS_CHANGED", "Payment Status Changed"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("object_reference", models.CharField(blank=True, max_length=255)),
                ("before_data", models.JSONField(blank=True, default=dict)),
                ("after_data", models.JSONField(blank=True, default=dict)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("path", models.CharField(blank=True, max_length=1000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audit_logs__event_t_b55aa4_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_logs__actor_i_cf3393_idx",
                    ),
                    models.Index(
                        fields=["app_label", "model_name", "object_id"],
                        name="audit_logs__app_lab_0b47ba_idx",
                    ),
                    models.Index(
                        fields=["request_id", "created_at"],
                        name="audit_logs__request_7ada7b_idx",
                    ),
                ],
            },
        ),
    ]
