# Generated by Django 6.0.7 on 2026-07-24 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_address_options_and_more"),
        ("shipping_rates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_max_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_min_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="free_shipping_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shipping_rates.shippingmethod",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shipping_rates.shippingzone",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shipping_method_code", "created_at"],
                name="orders_orde_shippin_69669b_idx",
            ),
        ),
    ]
