# Generated by Django 6.0.7 on 2026-07-24 05:53

import apps.store_settings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="Ecommerce Store", max_length=150),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store/settings/logo/",
                        validators=[apps.store_settings.models.validate_store_image],
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store/settings/favicon/",
                        validators=[apps.store_settings.models.validate_store_image],
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=30)),
                ("whatsapp_number", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Pakistan", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("currency_code", models.CharField(default="PKR", max_length=10)),
                ("currency_symbol", models.CharField(default="Rs.", max_length=10)),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "return_window_days",
                    models.PositiveIntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "order_cancellation_window_hours",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.CharField(
                        blank=True,
                        default="The store is temporarily unavailable. Please try again later.",
                        max_length=500,
                    ),
                ),
                ("allow_cash_on_delivery", models.BooleanField(default=True)),
                ("allow_bank_transfer", models.BooleanField(default=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
