# Generated by Django 6.0.7 on 2026-07-24 05:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="shipping_ra_is_acti_4596bb_idx",
                    ),
                    models.Index(
                        fields=["is_default", "is_active"],
                        name="shipping_ra_is_defa_fc7cc1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("country", models.CharField(default="Pakistan", max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher priority zones are selected first when multiple zones match.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["country", "province", "city", "is_active"],
                        name="shipping_ra_country_40c067_idx",
                    ),
                    models.Index(
                        fields=["is_active", "priority"],
                        name="shipping_ra_is_acti_25f084_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "estimated_min_days",
                    models.PositiveIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estimated_max_days",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("cod_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping_rates.shippingmethod",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping_rates.shippingzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone__name", "method__display_order"],
                "indexes": [
                    models.Index(
                        fields=["zone", "method", "is_active"],
                        name="shipping_ra_zone_id_39a909_idx",
                    ),
                    models.Index(
                        fields=["cod_available", "is_active"],
                        name="shipping_ra_cod_ava_fa9c6c_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "method"),
                        name="unique_shipping_rate_per_zone_method",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("charge__gte", 0)),
                        name="shipping_rate_charge_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("free_shipping_threshold__isnull", True),
                            ("free_shipping_threshold__gte", 0),
                            _connector="OR",
                        ),
                        name="shipping_free_threshold_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estimated_min_days__gte", 1)),
                        name="shipping_min_days_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estimated_max_days__gte", 1)),
                        name="shipping_max_days_positive",
                    ),
                ],
            },
        ),
    ]
