# Generated by Django 6.0.7 on 2026-07-24 03:04

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        default=apps.payments.models.generate_payment_number,
                        editable=False,
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH_ON_DELIVERY", "Cash on Delivery"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=100)),
                (
                    "proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.payments.models.payment_proof_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp", "pdf"]
                            ),
                            apps.payments.models.validate_payment_proof_size,
                        ],
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payment_number"], name="payments_pa_payment_a0847d_idx"
                    ),
                    models.Index(
                        fields=["customer", "status"],
                        name="payments_pa_custome_25a299_idx",
                    ),
                    models.Index(
                        fields=["method", "status"],
                        name="payments_pa_method_c0b72b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="payments_pa_created_b8a300_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("transaction_reference", ""), _negated=True
                        ),
                        fields=("transaction_reference",),
                        name="unique_non_empty_payment_reference",
                    )
                ],
            },
        ),
    ]
