# Generated by Django 6.0.7 on 2026-07-29 04:07

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=apps.products.models.category_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=apps.products.models.product_image_upload_path
            ),
        ),
    ]
