# Generated by Django 6.0.7 on 2026-07-24 03:56

import apps.shipments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_coupon_code_order_discount_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_number",
                    models.CharField(
                        default=apps.shipments.models.generate_shipment_number,
                        editable=False,
                        max_length=25,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready for Shipment"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("DELIVERY_FAILED", "Delivery Failed"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="READY",
                        max_length=30,
                    ),
                ),
                ("courier_name", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=150)),
                ("estimated_delivery_date", models.DateField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready for Shipment"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("DELIVERY_FAILED", "Delivery Failed"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipment_number"], name="shipments_s_shipmen_8b3960_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["status", "created_at"], name="shipments_s_status_67735e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["courier_name", "status"], name="shipments_s_courier_c0d827_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tracking_number", ""), _negated=True),
                fields=("tracking_number",),
                name="unique_non_empty_tracking_number",
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["shipment", "created_at"], name="shipments_s_shipmen_2a9f11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipmentevent",
            index=models.Index(
                fields=["status", "created_at"], name="shipments_s_status_467f71_idx"
            ),
        ),
    ]
