# Generated by Django 6.0.7 on 2026-07-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_order_estimated_delivery_end_and_more"),
        ("returns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Order Placed"),
                            ("ORDER_STATUS_CHANGED", "Order Status Changed"),
                            ("PAYMENT_STATUS_CHANGED", "Payment Status Changed"),
                            ("RETURN_STATUS_CHANGED", "Return Status Changed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("html_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="orders.order",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="returns.returnrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_type", "status", "created_at"],
                        name="email_notif_email_t_c0ebfb_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="email_notif_recipie_86ee73_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="email_notif_user_id_286456_idx",
                    ),
                    models.Index(
                        fields=["order", "created_at"],
                        name="email_notif_order_i_5516dd_idx",
                    ),
                    models.Index(
                        fields=["return_request", "created_at"],
                        name="email_notif_return__f97463_idx",
                    ),
                ],
            },
        ),
    ]
