# Generated by Django 6.0.7 on 2026-07-25 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("ORDER_STATUS_CHANGED", "Order Status Changed"),
                    ("PAYMENT_STATUS_CHANGED", "Payment Status Changed"),
                    ("SHIPMENT_STATUS_CHANGED", "Shipment Status Changed"),
                    ("TICKET_REPLY", "Ticket Reply"),
                    ("TICKET_STATUS_CHANGED", "Ticket Status Changed"),
                    ("RETURN_STATUS_CHANGED", "Return Status Changed"),
                    ("PROMOTIONAL", "Promotional Email"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="EmailNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_updates", models.BooleanField(default=True)),
                ("payment_updates", models.BooleanField(default=True)),
                ("shipment_updates", models.BooleanField(default=True)),
                ("ticket_updates", models.BooleanField(default=True)),
                ("return_updates", models.BooleanField(default=True)),
                ("promotional_emails", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
